name: 🤖 Auto-assign issue creator
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Add assignee = issue creator
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
